# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c4e0ce0da1ed3bc7abae1d7a825ef07173c0ea4c8b3d3663a62adff5b4b5f0752798a04c812445a26877a93f454ed38546d676de0cea413a2a75fc51f19a08e

test:
  secret_key_base: 6466159e2f5a427aabe5d865121f292b7284320a1c452f4499f8a0a989a505526206fb8dbd5b11a0d3f2c982dd2644b65170df6eb81cbcc508f73473748b00b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
